#!/usr/bin/env bash
#  compile test:
#  -o hw01.exe : name the compiled executable 'hw01.exe'
g++ -std=c++20 -Wall ../hw01.cpp -o hw01.exe

#  execute the test
if [[ -f "./hw01.exe" ]]; then
    ./hw01.exe
else
    echo "Resubmit your code and try again."
fi